disablePathToLower = true
languageCode = "en-us"
title = "Scott's Site"
theme = 'typo'

# Collection to display on home
[params]
theme = 'light'
homeCollectionTitle = 'Posts'
homeCollection = 'post'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

math = true

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/post"

[[params.menu]]
name = "about"
url = "/about"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'catppuccin-latte'
